apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
        - name: checkout-service
          image: nguyengoctu/checkout-service:1.0.6
          env:
            - name: PORT
              value: "7008"
            - name: DISABLE_PROFILER
              value: "1"
            - name: CURRENCY_SERVICE_ADDR
              value: "currency-service:7000"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "product-catalog-service:7002"
            - name: SHIPPING_SERVICE_ADDR
              value: "shipping-service:7003"
            - name: EMAIL_SERVICE_ADDR
              value: "email-service:7004"
            - name: CART_SERVICE_ADDR
              value: "cart-service:7006"
            - name: PAYMENT_SERVICE_ADDR
              value: "payment-service:7001"
