apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
        - name: currency-service
          image: nguyengoctu/currency-service:latest
          env:
            - name: PORT
              value: "7000"
            - name: DISABLE_PROFILER
              value: "1"
