apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  selector:
    app: product-catalog-service
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002
  type: ClusterIP
