name: Ad Service CI

on:
  push:
    branches: [main]
    paths:
      - "src/adservice/**"
      - ".github/workflows/adservice-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/adservice/**"
      - ".github/workflows/adservice-ci.yml"

env:
  JAVA_VERSION: "19"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/adservice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (includes tests)
        run: docker build -t adservice:latest .
