name: Microservices CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: ad-service
          - name: cart-service
          - name: checkout-service
          - name: currency-service
          - name: email-service
          - name: frontend
          - name: payment-service
          - name: product-catalog-service
          - name: recommendation-service
          - name: shipping-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch last 2 commits to compare changes

      - name: Check if VERSION file changed
        id: check_version
        uses: tj-actions/changed-files@v41
        with:
          files: VERSION

      - name: Build Docker image (includes tests)
        working-directory: ./src/${{ matrix.service.name }}
        run: docker build -t ${{ matrix.service.name }}:latest .

      - name: Read version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_version.outputs.any_changed == 'true'
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_version.outputs.any_changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_version.outputs.any_changed == 'true'
        run: |
          docker tag ${{ matrix.service.name }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ steps.version.outputs.VERSION }}
          docker tag ${{ matrix.service.name }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ steps.version.outputs.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:latest
